wp

diff --git a/.lib/ppt_core b/.lib/ppt_core
--- a/.lib/ppt_core
+++ b/.lib/ppt_core
@@ -3,6 +3,9 @@
 PPT_TRUE=0
 PPT_FALSE=1
 PPT_ERROR=2
+PPT_TITLE=${PPT_TITLE:-1}
+PPT_ALLOW_ROOT=${PPT_ALLOW_ROOT:-0}
+
 ### COLORS
 # Black        0;30     Dark Gray     1;30
 # Red          0;31     Light Red     1;31
@@ -17,10 +20,14 @@ PPT_ERROR=2
 __PPT_ANSI_DARK='\033[2m'
 
 __PPT_ANSI_NONE='\033[0m'
-__PPT_ANSI_RED='\033[1;31m'
-__PPT_ANSI_GREEN='\033[1;32m'
-__PPT_ANSI_YELLOW='\033[1;33m'
-__PPT_ANSI_CYAN='\033[1;36m'
+__PPT_ANSI_RED='\033[0;31m'
+__PPT_ANSI_BOLD_RED='\033[1;31m'
+__PPT_ANSI_GREEN='\033[0;32m'
+__PPT_ANSI_BOLD_GREEN='\033[1;32m'
+__PPT_ANSI_YELLOW='\033[0;33m'
+__PPT_ANSI_BOLD_YELLOW='\033[1;33m'
+__PPT_ANSI_CYAN='\033[0;36m'
+__PPT_ANSI_BOLD_CYAN='\033[1;36m'
 
 ### Define
 __ppt_reset_colors () {
@@ -30,6 +37,10 @@ __ppt_reset_colors () {
     __ppt_ansi_green=''
     __ppt_ansi_yellow=''
     __ppt_ansi_cyan=''
+    __ppt_ansi_bold_red=''
+    __ppt_ansi_bold_green=''
+    __ppt_ansi_bold_yellow=''
+    __ppt_ansi_bold_cyan=''
 }
 __ppt_set_colors () {
     __ppt_ansi_none=${__PPT_ANSI_NONE}
@@ -38,19 +49,23 @@ __ppt_set_colors () {
     __ppt_ansi_green=${__PPT_ANSI_GREEN}
     __ppt_ansi_yellow=${__PPT_ANSI_YELLOW}
     __ppt_ansi_cyan=${__PPT_ANSI_CYAN}
+    __ppt_ansi_bold_red=${__PPT_ANSI_BOLD_RED}
+    __ppt_ansi_bold_green=${__PPT_ANSI_BOLD_GREEN}
+    __ppt_ansi_bold_yellow=${__PPT_ANSI_BOLD_YELLOW}
+    __ppt_ansi_bold_cyan=${__PPT_ANSI_BOLD_CYAN}
 }
 ### Set defaults
 __ppt_reset_colors
 
 ### Logging functions.
 _ppt_warn() {
-  echo "${__ppt_ansi_yellow}ppt:WARN${__ppt_ansi_none} $*" >&2
+  echo "⚠️  ${__ppt_ansi_bold_yellow}ppt:WARN${__ppt_ansi_none} $*" >&2
 }
 _ppt_error() {
-  echo "${__ppt_ansi_red}ppt:ERROR${__ppt_ansi_none} $*" >&2
+  echo "🛑 ${__ppt_ansi_bold_red}ppt:ERROR${__ppt_ansi_none} $*" >&2
 }
 _ppt_fatal() {
-  echo "${__ppt_ansi_red}ppt:FATAL${__ppt_ansi_none} $*" >&2
+  echo "🔥 ${__ppt_ansi_bold_red}ppt:FATAL${__ppt_ansi_none} $*" >&2
   exit ${PPT_ERROR}
 }
 ### Messages functions
@@ -62,6 +77,9 @@ _ppt_info() {
 }
 _ppt_comment() {
   echo "${__ppt_ansi_yellow}$*${__ppt_ansi_none}" >&2
+}
+_ppt_notice() {
+  echo "${__ppt_ansi_bold_yellow}$*${__ppt_ansi_none}" >&2
 }
 
 
@@ -96,21 +114,30 @@ _ppt_configureColor() {
 _ppt_check_user () {
     if [ $(whoami) = "root" ]
     then
-        _ppt_fatal "DO NOT run this script under root!"
+        if [ ${PPT_ALLOW_ROOT} -eq 0 ]
+            then
+                _ppt_fatal "DO NOT run this script under root!"
+            fi
     fi
 }
 
 _ppt_set_terminal_title () {
-    echo "\033]0;${1}\007"
+    if [ ${PPT_TITLE} -eq 1 ]
+    then
+        printf "\033]0;${1}\007"
+    fi
 }
 
 
 _ppt_check_if_dir_exists  () {
     __DIRECTORY=$(_ppt_realpath "${1}")
-    if [ -d "${__DIRECTORY}" ]; then
-        if [ ! -L "${__DIRECTORY}" ]; then
-            unset __DIRECTORY
-            return ${PPT_TRUE}
+    if [ $? -eq ${PPT_TRUE} ]
+    then
+        if [ -d "${__DIRECTORY}" ]; then
+            if [ ! -L "${__DIRECTORY}" ]; then
+                unset __DIRECTORY
+                return ${PPT_TRUE}
+            fi
         fi
     fi
     unset __DIRECTORY
@@ -118,16 +145,18 @@ _ppt_check_if_dir_exists  () {
 }
 
 _ppt_settings_dir_is_consistent () {
-    FILES=""
-    FILES="${FILES} ${COMPOSER_JSON}"
-    FILES="${FILES} ${CHANGELOG_MD}"
-    FILES="${FILES} ${README_MD}"
-    for FILE in ${FILES}; do
-        if [ ! -e "${_PPT_SETTINGS_DIR}/${FILE}" ]
+    __PPT_FILES=""
+    __PPT_FILES="${__PPT_FILES} ${_COMPOSER_JSON}"
+    __PPT_FILES="${__PPT_FILES} ${_CHANGELOG_MD}"
+    __PPT_FILES="${__PPT_FILES} ${_README_MD}"
+    for __FILE in ${__PPT_FILES}; do
+        if [ ! -e "${_PPT_SETTINGS_DIR}/${__FILE}" ]
         then
-            _ppt_dark "Not found: ${_PPT_SETTINGS_DIR}/${FILE}"
+            _ppt_dark "Not found: ${_PPT_SETTINGS_DIR}/${__FILE}"
+            unset __PPT_FILES __FILE
             return ${PPT_FALSE}
         fi
     done
+    unset __PPT_FILES __FILE
     return ${PPT_TRUE}
 }
